[mypy]
python_version = 3.13
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disable_error_code = no-any-return

[mypy-homeassistant.*]
ignore_missing_imports = True

[mypy-pytest.*]
ignore_missing_imports = True

[mypy-aiohttp.*]
ignore_missing_imports = True

[mypy-voluptuous.*]
ignore_missing_imports = True

[mypy-async_timeout.*]
ignore_missing_imports = True

[mypy-pytest_homeassistant_custom_component.*]
ignore_missing_imports = True

[mypy-librt.*]
ignore_missing_imports = True
