name: Validations

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  release:
    types: [published]
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"

  validate-hassfest:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
